### PR TITLE
programme circular queue

### PR DESCRIPTION
**Pull request by Shanky1199**
things need to be updated
:-proper documentation

### CODE REVIEW

**Comment by haxzie-xx** [comment]
Read the instructions? :smile:

**Comment by haxzie-xx** [comment]
Comments please, so that students can understand the code better.

**Comment by Shanky1199** [comment]
umm basically i am bit lazy writing too much so sorry couldnt read the whole instruction but lets see who can update it better? watcha say

**Comment by haxzie-xx** [comment]
I hope someone does that.. 😂 You can assign someone if you are busy. Don't let it stay like this.

**Review by haxzie-xx — CHANGES_REQUESTED** [review]
Read the instructionsss carefullyyyyyyy :laughing:

**Pull request closed without merging**
